Wait for Tomcat to shutdown gracefully
LabKey/gradlePlugin pull request #79
Opened 2020-07-23 19:47 UTC by labkey-tchad

#### Rationale
`TeamCity.ensureShutdown` sometimes kills Tomcat before it is able to finish shutting down gracefully from the normal `stopTomcat` task. This is preventing shutdown listeners from logging JSP error counts, action stats, and query stats after some suites on TeamCity.

#### Changes
* Wait for Tomcat to shutdown gracefully before killing VM directly

2020-07-23 20:50 UTC, labkey-susanh requested changes

2020-07-23 20:50 UTC, labkey-susanh commented on src/main/groovy/org/labkey/gradle/plugin/TeamCity.groovy
> +        while (System.currentTimeMillis() - startTime > 15_000)
Don't you want `<` here?

2020-07-23 21:25 UTC, labkey-tchad commented on src/main/groovy/org/labkey/gradle/plugin/TeamCity.groovy
> +        while (System.currentTimeMillis() - startTime > 15_000)
Indeed I do.

2020-07-23 21:34 UTC, labkey-susanh approved these changes

2020-07-24 22:03 UTC, labkey-adam approved these changes

2020-07-24 22:03 UTC, labkey-adam commented on src/main/groovy/org/labkey/gradle/plugin/TeamCity.groovy
> +        while (System.currentTimeMillis() - startTime < 15_000)
Maybe create a constant for this (int seconds = 15) and reference it in the message below ("did not shutdown in __ seconds").

2020-07-24 22:29 UTC, merged